import {
	useFonts,
	Roboto_400Regular,
	Itim_400Regular,
	OpenSans_400Regular,
	Lato_400Regular,
	Montserrat_400Regular,
	RobotoCondensed_400Regular,
	Oswald_400Regular,
	Raleway_400Regular,
	Ubuntu_400Regular,
	Lora_400Regular,
	Rubik_400Regular,
	FiraSans_400Regular,
	Quicksand_400Regular,
	Oxygen_400Regular,
	Lobster_400Regular,
	Comfortaa_400Regular,
	Cairo_400Regular,
	Cinzel_400Regular,
	AbrilFatface_400Regular,
	BebasNeue_400Regular,
	MavenPro_400Regular,
} from '@expo-google-fonts/dev';

export const fonts = {
	'Itim': Itim_400Regular,
	'Open Sans': OpenSans_400Regular,
	'Roboto': Roboto_400Regular,
	//Sant-serif
	'Lato': Lato_400Regular,
	'Montserrat': Montserrat_400Regular,
	'Roboto Condensed': RobotoCondensed_400Regular,
	'Oswald': Oswald_400Regular,
	'Raleway': Raleway_400Regular,
	'Ubuntu': Ubuntu_400Regular,
	'Lora': Lora_400Regular,
	'Rubik': Rubik_400Regular,
	'Fira Sans': FiraSans_400Regular,
	'Quicksand': Quicksand_400Regular,
	'Oxygen': Oxygen_400Regular,
	'Lobster': Lobster_400Regular,
	'Comfortaa': Comfortaa_400Regular,
	'Cairo': Cairo_400Regular,
	'Cinzel': Cinzel_400Regular,
	'Abril Fatface': AbrilFatface_400Regular,
	'Bebas Neue': BebasNeue_400Regular,
	'Maven Pro': MavenPro_400Regular,
	'SF Pro Display': 'https://fontsfree.net//wp-content/fonts/basic/sans-serif/FontsFree-Net-SFProDisplay-Regular.ttf',
	'SF Pro Text': 'https://fontsfree.net//wp-content/fonts/basic/sans-serif/FontsFree-Net-SFProText-Regular.ttf',
	'SF Pro Rounded': 'https://fontsfree.net//wp-content/fonts/basic/sans-serif/FontsFree-Net-SF-Pro-Rounded-Regular.ttf',
	'SF Pro Text-Medium': 'https://fontsfree.net//wp-content/fonts/basic/sans-serif/FontsFree-Net-SFProText-Medium.ttf'
}
